const NxNotificationChannelPhoneCall = "phonecall"


template Notification "nx-nt-channel-phonecall" {
}

template Notification "nx-nt-channel-phonecall-for-host" {
        import "nx-nt-channel-phonecall"
        command = "nx-c-phonecall-notification"
}

template Notification "nx-nt-channel-phonecall-for-service" {
        import "nx-nt-channel-phonecall"
        command = "nx-c-phonecall-notification"

        vars.nx_notification_from_channel_override = (NxNotificationChannelPhoneCall in service.vars.nx_notification_basic_channels_override)
}


# Rules for Host Notification

apply Notification "nx-n-basic-phonecall-to-users-from-host" to Host {
        import "nx-nt-basic"
        import "nx-nt-channel-phonecall-for-host"

        users = host.vars.nx_notification_basic_users

        assign where nx_is_notification_channel_enabled(NxNotificationChannelPhoneCall, host.vars.nx_notification_basic_channels, null)
        ignore where !match("enabled_for_host*", host.vars.nx_notification_basic_mode_host)
        ignore where !(host.vars.nx_notification_basic_users)
}

apply Notification "nx-n-basic-phonecall-to-groups-from-host" to Host {
        import "nx-nt-basic"
        import "nx-nt-channel-phonecall-for-host"

        user_groups = host.vars.nx_notification_basic_groups

        assign where nx_is_notification_channel_enabled(NxNotificationChannelPhoneCall, host.vars.nx_notification_basic_channels, null)
        ignore where !match("enabled_for_host*", host.vars.nx_notification_basic_mode_host)
        ignore where !(host.vars.host.vars.nx_notification_basic_groups)
}


# Rules for Service Notification

apply Notification "nx-n-basic-phonecall-to-users-from-service" to Service {
        import "nx-nt-basic"
        import "nx-nt-channel-phonecall-for-service"

        if (service.vars.nx_notification_basic_users_override) {
                vars.nx_notification_use_users_override = true
                users = service.vars.nx_notification_basic_users_override
        } else {
                vars.nx_notification_use_users_override = false
                users = host.vars.nx_notification_basic_users
        }

        assign where nx_is_notification_channel_enabled(NxNotificationChannelPhoneCall, host.vars.nx_notification_basic_channels, service.vars.nx_notification_basic_channels_override)
        ignore where !(match("enabled_for_*services", host.vars.nx_notification_basic_mode_host))
        ignore where !(match ("enabled", service.vars.nx_notification_basic_mode_service))
        ignore where !(host.vars.nx_notification_basic_users) && !(service.vars.nx_notification_basic_users_override)
}

apply Notification "nx-n-basic-phonecall-to-groups-from-service" to Service {
        import "nx-nt-basic"
        import "nx-nt-channel-phonecall-for-service"

        if (service.vars.nx_notification_basic_groups_override) {
                vars.nx_notification_use_groups_override = true
                user_groups = service.vars.nx_notification_basic_groups_override
        } else {
                vars.nx_notification_use_groups_override = false
                user_groups = host.vars.nx_notification_basic_groups
        }

        assign where nx_is_notification_channel_enabled(NxNotificationChannelPhoneCall, host.vars.nx_notification_basic_channels, service.vars.nx_notification_basic_channels_override)
        ignore where !(match("enabled_for_*services", host.vars.nx_notification_basic_mode_host))
        ignore where !(match ("enabled", service.vars.nx_notification_basic_mode_service))
        ignore where !(host.vars.nx_notification_basic_groups) && !(service.vars.nx_notification_basic_groups_override)
}
