### NEP DEPENDENCY FILE ##################################################
# This file is provided by package nep-common and should not be changed: #
# Future nep updates will rewrite this file.                             #
# In case of changes, create your own dependencies.                      #
##########################################################################

apply Dependency "nx-disable-checks-on-host-down-hard" to Service {
  ignore_soft_states = true
  disable_checks = true

  assign where service.vars.nx_on_host_down == "disable_check_on_down_hard"
}

apply Dependency "nx-disable-checks-on-host-down-soft" to Service {
  ignore_soft_states = false
  disable_checks = true

  assign where service.vars.nx_on_host_down == "disable_check_on_down_soft"
}
