### NEP DEPENDENCY FILE #####################################################
# This file is provided by package nep-dbms-base and should not be changed: #
# Future nep updates will rewrite this file.                                #
# In case of changes, create your own dependencies.                         #
#############################################################################


## Dependencies for objects that have a DBMS Server as Parent
apply Dependency "nx-disable-notifications-on-parent-dbms-server-down " to Host {
  parent_host_name = host.vars.nx_parent_dbms_server

  states = [ Up ]
  disable_checks = false
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_parent_dbms_server
}

apply Dependency "nx-disable-notifications-on-parent-dbms-server-down " to Service {
  parent_host_name = host.vars.nx_parent_dbms_server

  states = [ Up ]
  disable_checks = false
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_parent_dbms_server
}


## Dependencies for objects that have a DBMS Instance as Parent
apply Dependency "nx-disable-notifications-on-parent-dbms-instance-down " to Host {
  parent_host_name = host.vars.nx_parent_dbms_instance

  states = [ Up ]
  disable_checks = false
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_parent_dbms_instance
}

apply Dependency "nx-disable-notifications-on-parent-dbms-instance-down " to Service {
  parent_host_name = host.vars.nx_parent_dbms_instance

  states = [ Up ]
  disable_checks = false
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_parent_dbms_instance
}
