{
 "title": "centreon_vectra",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": "${VAR_HOSTNAME}" },
   { "name": "service", "query": "${VAR_SERVICE}" },
   { "name": "command", "query": "${VAR_COMMAND}" }
  ]
 },
 "panels": [
  {
   "title": "centreon_vectra_cpu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nx-c-centreon_vectra_cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "cpu.utilization.percentage" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "centreon_vectra_memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nx-c-centreon_vectra_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "memory.usage.percentage" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "centreon_vectra_disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Disk Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nx-c-centreon_vectra_disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "disk.usage.percentage" }
     ]
    }
   ]
  },
  {
   "title": "centreon_vectra_sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nx-c-centreon_vectra_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  }
 ]
}