# Common settings for all basic notifications
template Notification "nx-nt-basic" {
	import "nx-nt-base"
	interval = number(host.vars.nx_notification_basic_interval)
	times.begin = number(host.vars.nx_notification_basic_delay)
}

# Determine if the Notification Channel is enabled On Host Object or though the Channel Override in Service Object
function nx_is_notification_channel_enabled(channel_name, host_channels_list, service_channels_list) {
        # Channel configured on Host and not on Service
        if (channel_name in host_channels_list && !(service_channels_list)){
                return true
        }
        # Channel configured on Service
        if (channel_name in service_channels_list){
                 return true
        }
        return false
}

# DEPRECATED. Please use function nx_is_notification_channel_enabled instead
# Verify Notification Channel definition on Service
# Verify Notification Channel definition on Service
function verify_service_channel(host_channels, service_channels, channel_name) {
        # Channel configured on Host and not on Service
        if (channel_name in host_channels && !(service_channels)){
                return true
        }
        # Channel configured on Service
        if (channel_name in service_channels){
                 return true
        }
        return false
}
