### NEP DEPENDENCY FILE ##################################################
# This file is provided by package nep-common and should not be changed: #
# Future nep updates will rewrite this file.                             #
# In case of changes, create your own dependencies.                      #
##########################################################################

apply Dependency "nx-disable-notifications-on-parent-down " for (parent in host.vars.nx_parent_hosts) to Host {
  parent_host_name = parent

  states = [ Up ]
  disable_checks = false
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_parent_hosts && (host.vars.nx_on_parent_disconnected == "disable-notifications")
}

apply Dependency "nx-disable-monitoring-on-parent-down " for (parent in host.vars.nx_parent_hosts) to Host {
  parent_host_name = parent

  states = [ Up ]
  disable_checks = true
  disable_notifications = false
  ignore_soft_states = true
  assign where host.vars.nx_parent_hosts && (host.vars.nx_on_parent_disconnected == "disable-monitoring")
}

apply Dependency "nx-disable-notifications-and-monitoring-on-parent-down " for (parent in host.vars.nx_parent_hosts) to Host {
  parent_host_name = parent

  states = [ Up ]
  disable_checks = true
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_parent_hosts && (host.vars.nx_on_parent_disconnected == "disable-notifications-and-monitoring")
}

