### NEP DEPENDENCY FILE ##################################################
# This file is provided by package nep-common and should not be changed: #
# Future nep updates will rewrite this file.                             #
# In case of changes, create your own dependencies.                      #
##########################################################################

apply Dependency "nx-disable-notifications-on-icinga-agent-disconnected" to Service {
  parent_service_name = "Icinga agent Status"

  states = [ OK ]
  disable_checks = false
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_monitored_by_icinga_agent &&  service.vars.nx_monitored_by_icinga_agent && (service.vars.nx_on_icinga_agent_disconnected == "disable-notifications")
}

apply Dependency "nx-disable-monitoring-on-icinga-agent-disconnected" to Service {
  parent_service_name = "Icinga agent Status"

  states = [ OK ]
  disable_checks = true
  disable_notifications = false
  ignore_soft_states = true
  assign where host.vars.nx_monitored_by_icinga_agent && service.vars.nx_monitored_by_icinga_agent && (service.vars.nx_on_icinga_agent_disconnected == "disable-monitoring")
}

apply Dependency "nx-disable-notifications-and-monitoring-on-icinga-agent-disconnected" to Service {
  parent_service_name = "Icinga agent Status"

  states = [ OK ]
  disable_checks = true
  disable_notifications = true
  ignore_soft_states = true
  assign where host.vars.nx_monitored_by_icinga_agent && service.vars.nx_monitored_by_icinga_agent && (service.vars.nx_on_icinga_agent_disconnected == "disable-notifications-and-monitoring")
}

