# File Format is the one supported by Python Configparser
# Get more info at: https://docs.python.org/3/library/configparser.html

### Package schema info
[NEP-SETUP]
# Pack schema version
stage=/usr/share/neteye/nep/
packages_root=/neteye/shared/nep/
packages=/neteye/shared/nep/data/packages/
