# Configuration file for creating timeperiods in neteye.
# The file must be compiled in this way:
# [NAME NATION].
# nation = <ISO 3166-1 alpha-2 country code >
# region = either empty, or region specific holidays. Depends on availability, refer to https://pypi.org/project/holidays/ for more information 

[Italy]
nation = IT
# region = BZ

# [Germany]
# nation = DE
# region = BW

# [Malaysia]
# nation = MY
