# Configuration file for creating timeperiods in neteye.
# The file must be compiled in this way:
# [NAME NATION].
# nation = <ISO 3166-1 alpha-2 country code >

[Italy]
nation = IT

#[Germany]
#nation = DE

#[France]
#nation = FR