apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: nep-build-and-test
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, maint-*]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  serviceAccountName: pipeline
  pipelineRef:
    resolver: git
    params:
      - name: gitToken
        value: "git-resolver"
      - name: pathInRepo
        value: rhel8-neteye-build/rhel8-neteye-build.yaml
      - name: revision
        value: "master"
  timeouts:
    pipeline: "0h30m0s"
    tasks: "0h20m0s"
    finally: "0h10m0s"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-cephfs-sing-rep
          volumeMode: Filesystem
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
  params:
    - name: version
      value: "{{ source_branch }}"
    - name: projects
      value: "gh-pub:nep:{{ source_branch }}"
    - name: releaseTag
      value: "alpha"
    - name: skipTests
      value: "true"
    - name: destroyVMs
      value: "true"
