apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: nep-build-and-test
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, maint-*]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  serviceAccountName: pipeline
  pipelineRef:
    resolver: git
    params:
      - name: gitToken
        value: "git-resolver"
      - name: pathInRepo
        value: rhel8-neteye-build/contrib-build-and-release.yaml
      - name: revision
        value: "master"
  timeouts:
    pipeline: "0h30m0s"
    tasks: "0h20m0s"
    finally: "0h10m0s"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-cephfs-sing-rep
          volumeMode: Filesystem
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
  params:
    # This project is used only by RD to test the build so we don't want to release packages in case we touch
    # the spec file. If we need to do so we can run the pipeline manually
    - name: useTestingRepos
      value: "true"
    - name: taskRevision
      value: "master"
    - name: version
      value: "{{ target_branch }}"
    - name: sourceGitBranch
      value: "{{ source_branch }}"

