name: Backport

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  backport:
    uses: neteye-platform/repo-commons/.github/workflows/backport.yaml@c6e0d2004a3a34a6249abb7e1b2863fb85270b60 # main
    secrets: inherit
