name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"
  merge_group:

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@c6e0d2004a3a34a6249abb7e1b2863fb85270b60 # main
    secrets: inherit
