name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"
  merge_group:

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@ad37f4c48a90763aa6e7e2d4e7fe39b529b984f3 # main
    secrets: inherit
