name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@ad37f4c48a90763aa6e7e2d4e7fe39b529b984f3 # main
    secrets: inherit
