name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@c6e0d2004a3a34a6249abb7e1b2863fb85270b60 # main
    secrets: inherit
